FROM nginx:alpine

# remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

# custom config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# copy frontend files
COPY . /usr/share/nginx/html

EXPOSE 80
